name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']  # Ensure version is quoted

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create false  # Optionally avoid creating virtual environments

    - name: Install dependencies using Poetry
      run: |
        poetry install --no-dev  # Skip dev dependencies if not needed for running tests

    - name: Run tests
      run: |
        poetry run pytest
